name: Build SWU tools

on:
  workflow_dispatch:
  
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - run: |
        docker run --rm -e KOBRA_MODEL_CODE="K3" -v ${{ github.workspace }}/build:/build -v ${{ github.workspace }}/files:/files ghcr.io/jbatonnet/rinkhals/build /bin/bash -c "chmod +x /build/swu-tools/ssh/build-swu.sh && /build/swu-tools/ssh/build-swu.sh /build/dist/tool-ssh.swu"
        docker run --rm -e KOBRA_MODEL_CODE="K3" -v ${{ github.workspace }}/build:/build -v ${{ github.workspace }}/files:/files ghcr.io/jbatonnet/rinkhals/build /bin/bash -c "chmod +x /build/swu-tools/backup-partitions/build-swu.sh && /build/swu-tools/backup-partitions/build-swu.sh /build/dist/tool-backup-partitions.swu"
        docker run --rm -e KOBRA_MODEL_CODE="K3" -v ${{ github.workspace }}/build:/build -v ${{ github.workspace }}/files:/files ghcr.io/jbatonnet/rinkhals/build /bin/bash -c "chmod +x /build/swu-tools/debug-bundle/build-swu.sh && /build/swu-tools/debug-bundle/build-swu.sh /build/dist/tool-debug-bundle.swu"
        docker run --rm -e KOBRA_MODEL_CODE="K3" -v ${{ github.workspace }}/build:/build -v ${{ github.workspace }}/files:/files ghcr.io/jbatonnet/rinkhals/build /bin/bash -c "chmod +x /build/swu-tools/cfg-reset/build-swu.sh && /build/swu-tools/cfg-reset/build-swu.sh /build/dist/tool-cfg-reset.swu"

    - name: Archive production artifacts
      uses: actions/upload-artifact@v4
      with:
        name: tools-k2p-k3
        path: |
          build/dist/*.swu

    - run: |
        docker run --rm -e KOBRA_MODEL_CODE="KS1" -v ${{ github.workspace }}/build:/build -v ${{ github.workspace }}/files:/files ghcr.io/jbatonnet/rinkhals/build /bin/bash -c "chmod +x /build/swu-tools/ssh/build-swu.sh && /build/swu-tools/ssh/build-swu.sh /build/dist/tool-ssh.swu"
        docker run --rm -e KOBRA_MODEL_CODE="KS1" -v ${{ github.workspace }}/build:/build -v ${{ github.workspace }}/files:/files ghcr.io/jbatonnet/rinkhals/build /bin/bash -c "chmod +x /build/swu-tools/backup-partitions/build-swu.sh && /build/swu-tools/backup-partitions/build-swu.sh /build/dist/tool-backup-partitions.swu"
        docker run --rm -e KOBRA_MODEL_CODE="KS1" -v ${{ github.workspace }}/build:/build -v ${{ github.workspace }}/files:/files ghcr.io/jbatonnet/rinkhals/build /bin/bash -c "chmod +x /build/swu-tools/debug-bundle/build-swu.sh && /build/swu-tools/debug-bundle/build-swu.sh /build/dist/tool-debug-bundle.swu"
        docker run --rm -e KOBRA_MODEL_CODE="KS1" -v ${{ github.workspace }}/build:/build -v ${{ github.workspace }}/files:/files ghcr.io/jbatonnet/rinkhals/build /bin/bash -c "chmod +x /build/swu-tools/cfg-reset/build-swu.sh && /build/swu-tools/cfg-reset/build-swu.sh /build/dist/tool-cfg-reset.swu"

    - name: Archive production artifacts
      uses: actions/upload-artifact@v4
      with:
        name: tools-ks1
        path: |
          build/dist/*.swu
